### ISSUE TITLE
Improve diff matching

### ISSUE THREAD

**Issue by xlc** [chevdor/subwasm#14]
It should match against with the real module index, not sequence order.

e.g. This diff is indicating a very big change but it is caused by comparing wrong modules.
https://github.com/AcalaNetwork/Acala/issues/1256#issuecomment-888203916

```
🛠  modules.21.index.                                                    50 --> 45
🛠  modules.21.name.                                            "XcmpQueue" --> "SessionManager"
```

This just means it is comparing the wrong thing.

**Comment by chevdor** [comment]
👍 I noticed that as well. Thanks for the report.

**Comment by chevdor** [comment]
Closing this issue now as the version 0.20.0 is doing a much better job. Check both the `diff` and the new `show` commands.
