### ISSUE TITLE
readme gripe: metadata isn't really a fingerprint

### ISSUE THREAD

**Issue by JoshOrndorff** [chevdor/subwasm#20]
The readme explains that the metadata of a runtime can be used as a fingerprint for a runtime. While I agree this can be useful for a quick-n-dirty comparisons it really offers limited guarantees that the extrinsic signatures and some other superficial things look the same.

Two runtimes could have the same metadata but different behavior.

**Comment by chevdor** [comment]
You are right, I will review that part.
