### ISSUE TITLE
[deps]: pin git dependencies to a certain `rev`

### ISSUE THREAD

**Issue by niklasad1** [chevdor/subwasm#34]
This should be done to ensure older versions of this library still works.

See https://github.com/polkascan/py-subwasm-bindings/issues/1 for motivation for example

**Comment by chevdor** [comment]
Hi @niklasad1, I am a little confused by your statement:

> The problem is that subwasm is using latest master for jsonrpsee and v0.6.0 relied on old version that had many breaking changes.

as `subwasm` uses:
```
jsonrpsee = {version = "0.4", git = "https://github.com/paritytech/jsonrpsee", features = ["full"]}
```
and its cargo.lock has jsonrpsee pinned to:
```
version = "0.4.1"
source = "git+https://github.com/paritytech/jsonrpsee#ff3337b107bf29bef6067164c20c6a0b0b5bdc75"
```

The dependency on jsonrpsee master was likely true in the past though.

So it sounds like `py-subwasm` should upgrade its deps but do you see anything to be done the `suwbasm` side ?

**Comment by niklasad1** [comment]
Ah, I think I got confused by that you use both `git and version` in Cargo.toml

nvm
