### ISSUE TITLE
Transport(Invalid URL: No port number in URL (default port is not supported)) for get and info method

### ISSUE THREAD

**Issue by hunte-star** [chevdor/subwasm#40]
`While getting runtime`
![image](https://user-images.githubusercontent.com/93315244/145773410-cf48e2a3-a8e0-4b06-960f-780b23941ddd.png)

`While getting node info`
![image](https://user-images.githubusercontent.com/93315244/145773685-f9d949be-8a48-467e-9ce0-a8a8c307d061.png)

**Comment by chevdor** [comment]
dup #36
