### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by sander2** [chevdor/subwasm#42]
I was doing a `cargo install subwasm`, but got these errors:

```
error[E0432]: unresolved imports `clap::crate_authors`, `clap::crate_version`, `clap::Clap`
 --> /home/sander/.cargo/registry/src/github.com-1ecc6299db9ec823/subwasm-0.13.2/src/opts.rs:1:12
  |
1 | use clap::{crate_authors, crate_version, AppSettings, Clap};
  |            ^^^^^^^^^^^^^  ^^^^^^^^^^^^^               ^^^^ no `Clap` in the root
  |            |              |
  |            |              no `crate_version` in the root
  |            no `crate_authors` in the root

error[E0432]: unresolved imports `clap::crate_name`, `clap::crate_version`, `clap::Clap`
 --> /home/sander/.cargo/registry/src/github.com-1ecc6299db9ec823/subwasm-0.13.2/src/main.rs:3:12
  |
3 | use clap::{crate_name, crate_version, Clap};
  |            ^^^^^^^^^^  ^^^^^^^^^^^^^  ^^^^ no `Clap` in the root
  |            |           |
  |            |           no `crate_version` in the root
  |            no `crate_name` in the root
[...]
```

**Comment by chevdor** [comment]
Unfortunately, the `subwasm`crates is being squatted and the owner is not responding to my request to transfer the project. 
Crates.io is also not willing to help.
He is also not updating the code which explains your issue. I am not related to this person and I can only warn about whatever code is on crates.io

The only thing I can currently do is suggest NOT using `cargo install subwasm` so you do not install the squatted https://crates.io/crates/subwasm

Do feel free to ping the crate owner if you wish but I doubt that will help much.

Instead, I suggest building from source as [documented in the readme](https://github.com/chevdor/subwasm#using-cargo).
