### ISSUE TITLE
Configurable pallet ids

### ISSUE THREAD

**Issue by sander2** [chevdor/subwasm#45]
Currently the prefixes used to calculate `AuthorizeUpgrade` hashes are [hardcoded](https://github.com/chevdor/subwasm/blob/master/libs/substrate-runtime-proposal-hash/src/lib.rs#L17). In our case, they are incorrect. It would be great if there were some way to customize this.

**Comment by chevdor** [comment]
Hello @sander2,
How do you imagine a solution that would work for you ? What prefixes are you using ?
Could you give me a sample call and result hash as well as one of your runtimes for instance ?

As option, I could leave the current prefixes as default but allow you overriding them with ENVs. Would that be enough for your usecase ?

**Comment by sander2** [comment]
Our ParachainSystem pallet is [at index 32](https://github.com/interlay/interbtc/blob/95f2ea983de086d7cc53cb6469efae681831ccad/parachain/runtime/kintsugi/src/lib.rs#L1016) so I guess our used prefix would be `[32, 3]` instead of the default `[1, 3]`. I think using ENV to overwrite the default as you suggested would work well

**Comment by chevdor** [comment]
Could you check if [this PR](https://github.com/chevdor/subwasm/pull/46) would solve your problem ?

Just set `PARACHAIN_PALLET_ID_ENV=0x32` before running `subwasm` as usual.

**Comment by sander2** [comment]
Thanks for the PR! It doesn't fully address my problem yet - apparently the version of ParachainSystem that we use has `authorizeUpgrade` at method index 2. So I need to set the prefix to `[32, 2]`. So I would propose to make `PARACHAIN_PALLET_ID` a two-byte prefix, so in my case I would set `PARACHAIN_PALLET_ID_ENV=0x2002`

**Comment by chevdor** [comment]
ok, I see what you want, I am not sure I like the naming you suggest and the aggregation of the 2 IDs. It may be better to have simply a second ENV for the call. That will scale better if people need other calls as well so pallet id and call id are separated.

**Comment by sander2** [comment]
I agree that the naming I used wasn't appropriate - `AUTHORIZE_UPGRADE_PREFIX` would be better. Having two separate env variables would also be ok
