### ISSUE TITLE
Deps Broken

### ISSUE THREAD

**Issue by AurevoirXavier** [chevdor/subwasm#47]
Fixed in https://github.com/chevdor/subwasm/pull/44
Re-introduced in https://github.com/chevdor/subwasm/commit/113e0afdf58b22951bf8fe46b036f19a70e51605

**Comment by AurevoirXavier** [comment]
```
error: failed to select a version for the requirement `jsonrpsee = "^0.13"`
candidate versions found which didn't match: 0.14.0
location searched: Git repository https://github.com/paritytech/jsonrpsee
required by package `wasm-loader v0.17.1 (https://github.com/chevdor/subwasm#ce5b6951)`
    ... which satisfies git dependency `wasm-loader` of package `runtime-overrides v0.1.0 (/root/Codes/darwinia-network/runtime-overrides)`
```

**Comment by AurevoirXavier** [comment]
Please lock on tag or branch.
Otherwise, all the downstream packages will be broken.

**Comment by chevdor** [comment]
Did you build/run using `--locked` ?
I am aware of deps issues. I want to bring back all to substrate master.

**Comment by AurevoirXavier** [comment]
> Did you build/run using `--locked` ?
> I am aware of deps issues. I want to bring back all to substrate master.

Nope. Just `cargo update`.

**Comment by chevdor** [comment]
Ok, I'd suggest using `-locked` until this is fixed. I am aware of the issue.

**Comment by AurevoirXavier** [comment]
Nope. My goal is to upgrade the subwasm I don't want to use `--locked`.

It's okay if you want to keep the latest upgrade with substrate.
I recommend you create a tag like substrate. `polkadot-vx.x.x` for the third party usage.

**Comment by AurevoirXavier** [comment]
```
error: failed to select a version for the requirement `jsonrpsee = "^0.14"`
candidate versions found which didn't match: 0.15.1
location searched: Git repository https://github.com/paritytech/jsonrpsee
required by package `wasm-loader v0.18.0 (https://github.com/chevdor/subwasm?tag=v0.18.0#f0ebe6db)`
    ... which satisfies git dependency `wasm-loader` of package `runtime-overrides v0.1.0 (/root/code/darwinia-network/runtime-overrides)`
```

**Comment by chevdor** [comment]
What command are you using ? I would like to see the issue on my end.

**Comment by AurevoirXavier** [comment]
```
git clone https://github.com/darwinia-network/runtime-overrides.git
cd runtime-overrides
git checkout 4a51a7c05b85511927a79849392aa339364a812e
cargo update
```

**Comment by chevdor** [comment]
Thanks for the snippet, I can reproduce your issue.

**Comment by AurevoirXavier** [comment]
Said. It can still be reproduced in 2023 with tag 0.19.1.
