### ISSUE TITLE
Subwasm differ v1.0.0-alpha8 shows for Compatible and Require transaction_version bump as true at the same time 

### ISSUE THREAD

**Issue by EgorPopelyaev** [chevdor/subwasm#72]
### Current behavior

Running command like:
`subwasm diff -n collectives-polkadot_runtime-v9420.compact.compressed.wasm collectives-polkadot_runtime-v9430.compact.compressed.wasm`
Leads to the following oputput:
```
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
[≠] pallet 0: System -> 1 change(s)
  - constants changes:
    [≠] Version: [ 44, 99, 111, 108, 108, 101, 99, 116, 105, 118, 101, 115, 44, 99, 111, 108, 108, 101, 99, 116, 105, 118, 101, 115, 1, 0, 0, 0, 204, 36, 0, 0, ... ]
        [Value([Changed(28, U8Change(204, 214))])]

SUMMARY:
- Compatible.......................: true
- Require transaction_version bump.: true

!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
```
Which says that wasm's are **Compatible** and **Txn version bump is needed** at the same time.

The runtimes are taken from:
- [v9420](https://github.com/paritytech/cumulus/releases/download/parachains-v9420/collectives-polkadot_runtime-v9420.compact.compressed.wasm)
- [v9430-rc1](https://github.com/paritytech/cumulus/releases/download/untagged-ca1a61d0d0eeddca22e6/collectives-polkadot_runtime-v9430.compact.compressed.wasm)

**Comment by chevdor** [comment]
Thanks @EgorPopelyaev. Both true could happen but in your example, I would expect the Require transaction_version bump. to be false. I will double check.

**Comment by chevdor** [comment]
[westmint_runtime-v9430.compact.compressed.wasm.zip](https://github.com/chevdor/subwasm/files/11600389/westmint_runtime-v9430.compact.compressed.wasm.zip)
[westmint_runtime-v9420.compact.compressed.wasm.zip](https://github.com/chevdor/subwasm/files/11600390/westmint_runtime-v9420.compact.compressed.wasm.zip)
