### ISSUE TITLE
Date in version string leads to build reproducibility issues

### ISSUE THREAD

**Issue by andresilva** [chevdor/subwasm#94]
As the issue title says, in the nix derivation I had to mock the date command to workaround this (https://github.com/andresilva/polkadot.nix/commit/3a130979b091765b59e34019ada84129aa3efa23). Since the build date goes in the version string, depending on when a binary is built it would lead to a different checksum.

```
❯ subwasm --version                 
subwasm v0.21.2-fd2964a built 1980-01-01T00:00:00Z
```

**Comment by chevdor** [comment]
This is indeed an issue for the wasm itselves but why would that be an issue for subwasm ?

**Comment by andresilva** [comment]
Hace a look [here] (https://reproducible-builds.org/) for some background. 

But in general it means that as a package maintainer I can publish a built package with a given hash, and if you try to rebuild the package according to its definition you get a different hash. Ideally rebuilding the package according to its definition should yield the exact same binary. NixOS takes this quite seriously, but I think other distros also have efforts to provide reproducible builds (I know [Debian](https://wiki.debian.org/ReproducibleBuilds) tries at least).

**Comment by chevdor** [comment]
I see. Honnestly, this timestamp is not super critical. I don't have much time right now but if this is on your way, feel free to submit a "dirty" PR simply removing the version from the version string and create an issue for the clean up of the rest so it can be done later.
